DO
$$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aura_service') THEN
        CREATE ROLE aura_service LOGIN PASSWORD 'aura_service' BYPASSRLS;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'aura_app') THEN
        CREATE ROLE aura_app LOGIN PASSWORD 'aura_app' NOBYPASSRLS;
    END IF;
END
$$;

GRANT CONNECT ON DATABASE aura TO aura_service;
GRANT CONNECT ON DATABASE aura TO aura_app;
GRANT CREATE ON DATABASE aura TO aura_service;
GRANT USAGE, CREATE ON SCHEMA public TO aura_service;
GRANT USAGE ON SCHEMA public TO aura_app;

ALTER DEFAULT PRIVILEGES FOR ROLE aura_service IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO aura_app;

ALTER DEFAULT PRIVILEGES FOR ROLE aura_service IN SCHEMA public
GRANT USAGE, SELECT ON SEQUENCES TO aura_app;
